# CMake generated Testfile for 
# Source directory: /Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/network/examples
# Build directory: /Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/cmake-cache/src/network/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-bit-serializer "ns3.36.1-bit-serializer-default")
set_tests_properties(ctest-bit-serializer PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/network/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/network/examples/CMakeLists.txt;13;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/network/examples/CMakeLists.txt;0;")
add_test(ctest-main-packet-header "ns3.36.1-main-packet-header-default")
set_tests_properties(ctest-main-packet-header PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/network/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/network/examples/CMakeLists.txt;13;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/network/examples/CMakeLists.txt;0;")
add_test(ctest-main-packet-tag "ns3.36.1-main-packet-tag-default")
set_tests_properties(ctest-main-packet-tag PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/network/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/network/examples/CMakeLists.txt;13;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/network/examples/CMakeLists.txt;0;")
add_test(ctest-packet-socket-apps "ns3.36.1-packet-socket-apps-default")
set_tests_properties(ctest-packet-socket-apps PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/network/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/network/examples/CMakeLists.txt;13;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/network/examples/CMakeLists.txt;0;")
add_test(ctest-lollipop-comparisions "ns3.36.1-lollipop-comparisions-default")
set_tests_properties(ctest-lollipop-comparisions PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/network/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/network/examples/CMakeLists.txt;13;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/network/examples/CMakeLists.txt;0;")
