# CMake generated Testfile for 
# Source directory: /Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/wifi/examples
# Build directory: /Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/cmake-cache/src/wifi/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-wifi-phy-test "ns3.36.1-wifi-phy-test-default")
set_tests_properties(ctest-wifi-phy-test PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/wifi/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/wifi/examples/CMakeLists.txt;1;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/wifi/examples/CMakeLists.txt;0;")
add_test(ctest-wifi-test-interference-helper "ns3.36.1-wifi-test-interference-helper-default")
set_tests_properties(ctest-wifi-test-interference-helper PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/wifi/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/wifi/examples/CMakeLists.txt;11;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/wifi/examples/CMakeLists.txt;0;")
add_test(ctest-wifi-manager-example "ns3.36.1-wifi-manager-example-default")
set_tests_properties(ctest-wifi-manager-example PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/wifi/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/wifi/examples/CMakeLists.txt;21;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/wifi/examples/CMakeLists.txt;0;")
add_test(ctest-wifi-trans-example "ns3.36.1-wifi-trans-example-default")
set_tests_properties(ctest-wifi-trans-example PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/wifi/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/wifi/examples/CMakeLists.txt;33;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/wifi/examples/CMakeLists.txt;0;")
add_test(ctest-wifi-phy-configuration "ns3.36.1-wifi-phy-configuration-default")
set_tests_properties(ctest-wifi-phy-configuration PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/wifi/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/wifi/examples/CMakeLists.txt;45;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/wifi/examples/CMakeLists.txt;0;")
add_test(ctest-wifi-bianchi "ns3.36.1-wifi-bianchi-default")
set_tests_properties(ctest-wifi-bianchi PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/wifi/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/wifi/examples/CMakeLists.txt;52;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/wifi/examples/CMakeLists.txt;0;")
