# CMake generated Testfile for 
# Source directory: /Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/csma/examples
# Build directory: /Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/cmake-cache/src/csma/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-csma-one-subnet "ns3.36.1-csma-one-subnet-default")
set_tests_properties(ctest-csma-one-subnet PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/csma/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/csma/examples/CMakeLists.txt;11;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/csma/examples/CMakeLists.txt;0;")
add_test(ctest-csma-broadcast "ns3.36.1-csma-broadcast-default")
set_tests_properties(ctest-csma-broadcast PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/csma/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/csma/examples/CMakeLists.txt;11;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/csma/examples/CMakeLists.txt;0;")
add_test(ctest-csma-packet-socket "ns3.36.1-csma-packet-socket-default")
set_tests_properties(ctest-csma-packet-socket PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/csma/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/csma/examples/CMakeLists.txt;11;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/csma/examples/CMakeLists.txt;0;")
add_test(ctest-csma-multicast "ns3.36.1-csma-multicast-default")
set_tests_properties(ctest-csma-multicast PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/csma/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/csma/examples/CMakeLists.txt;11;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/csma/examples/CMakeLists.txt;0;")
add_test(ctest-csma-raw-ip-socket "ns3.36.1-csma-raw-ip-socket-default")
set_tests_properties(ctest-csma-raw-ip-socket PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/csma/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/csma/examples/CMakeLists.txt;21;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/csma/examples/CMakeLists.txt;0;")
add_test(ctest-csma-ping "ns3.36.1-csma-ping-default")
set_tests_properties(ctest-csma-ping PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/csma/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/csma/examples/CMakeLists.txt;31;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/csma/examples/CMakeLists.txt;0;")
