# CMake generated Testfile for 
# Source directory: /Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/wave/examples
# Build directory: /Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/cmake-cache/src/wave/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-wave-simple-80211p "ns3.36.1-wave-simple-80211p-default")
set_tests_properties(ctest-wave-simple-80211p PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/wave/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/wave/examples/CMakeLists.txt;1;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/wave/examples/CMakeLists.txt;0;")
add_test(ctest-wave-simple-device "ns3.36.1-wave-simple-device-default")
set_tests_properties(ctest-wave-simple-device PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/wave/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/wave/examples/CMakeLists.txt;13;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/wave/examples/CMakeLists.txt;0;")
add_test(ctest-vanet-routing-compare "ns3.36.1-vanet-routing-compare-default")
set_tests_properties(ctest-vanet-routing-compare PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/wave/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/wave/examples/CMakeLists.txt;25;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/wave/examples/CMakeLists.txt;0;")
