# CMake generated Testfile for 
# Source directory: /Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/traffic-control/examples
# Build directory: /Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/cmake-cache/src/traffic-control/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-red-tests "ns3.36.1-red-tests-default")
set_tests_properties(ctest-red-tests PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/traffic-control/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/traffic-control/examples/CMakeLists.txt;1;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/traffic-control/examples/CMakeLists.txt;0;")
add_test(ctest-red-vs-ared "ns3.36.1-red-vs-ared-default")
set_tests_properties(ctest-red-vs-ared PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/traffic-control/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/traffic-control/examples/CMakeLists.txt;12;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/traffic-control/examples/CMakeLists.txt;0;")
add_test(ctest-adaptive-red-tests "ns3.36.1-adaptive-red-tests-default")
set_tests_properties(ctest-adaptive-red-tests PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/traffic-control/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/traffic-control/examples/CMakeLists.txt;23;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/traffic-control/examples/CMakeLists.txt;0;")
add_test(ctest-pfifo-vs-red "ns3.36.1-pfifo-vs-red-default")
set_tests_properties(ctest-pfifo-vs-red PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/traffic-control/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/traffic-control/examples/CMakeLists.txt;34;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/traffic-control/examples/CMakeLists.txt;0;")
add_test(ctest-codel-vs-pfifo-basic-test "ns3.36.1-codel-vs-pfifo-basic-test-default")
set_tests_properties(ctest-codel-vs-pfifo-basic-test PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/traffic-control/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/traffic-control/examples/CMakeLists.txt;45;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/traffic-control/examples/CMakeLists.txt;0;")
add_test(ctest-codel-vs-pfifo-asymmetric "ns3.36.1-codel-vs-pfifo-asymmetric-default")
set_tests_properties(ctest-codel-vs-pfifo-asymmetric PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/traffic-control/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/traffic-control/examples/CMakeLists.txt;56;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/traffic-control/examples/CMakeLists.txt;0;")
add_test(ctest-pie-example "ns3.36.1-pie-example-default")
set_tests_properties(ctest-pie-example PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/traffic-control/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/traffic-control/examples/CMakeLists.txt;67;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/traffic-control/examples/CMakeLists.txt;0;")
add_test(ctest-fqcodel-l4s-example "ns3.36.1-fqcodel-l4s-example-default")
set_tests_properties(ctest-fqcodel-l4s-example PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/traffic-control/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/traffic-control/examples/CMakeLists.txt;78;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/traffic-control/examples/CMakeLists.txt;0;")
