# CMake generated Testfile for 
# Source directory: /Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/spectrum/examples
# Build directory: /Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/cmake-cache/src/spectrum/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-adhoc-aloha-ideal-phy "ns3.36.1-adhoc-aloha-ideal-phy-default")
set_tests_properties(ctest-adhoc-aloha-ideal-phy PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/spectrum/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/spectrum/examples/CMakeLists.txt;1;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/spectrum/examples/CMakeLists.txt;0;")
add_test(ctest-adhoc-aloha-ideal-phy-matrix-propagation-loss-model "ns3.36.1-adhoc-aloha-ideal-phy-matrix-propagation-loss-model-default")
set_tests_properties(ctest-adhoc-aloha-ideal-phy-matrix-propagation-loss-model PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/spectrum/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/spectrum/examples/CMakeLists.txt;11;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/spectrum/examples/CMakeLists.txt;0;")
add_test(ctest-adhoc-aloha-ideal-phy-with-microwave-oven "ns3.36.1-adhoc-aloha-ideal-phy-with-microwave-oven-default")
set_tests_properties(ctest-adhoc-aloha-ideal-phy-with-microwave-oven PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/spectrum/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/spectrum/examples/CMakeLists.txt;21;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/spectrum/examples/CMakeLists.txt;0;")
add_test(ctest-tv-trans-example "ns3.36.1-tv-trans-example-default")
set_tests_properties(ctest-tv-trans-example PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/spectrum/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/spectrum/examples/CMakeLists.txt;31;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/spectrum/examples/CMakeLists.txt;0;")
add_test(ctest-tv-trans-regional-example "ns3.36.1-tv-trans-regional-example-default")
set_tests_properties(ctest-tv-trans-regional-example PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/spectrum/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/spectrum/examples/CMakeLists.txt;40;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/spectrum/examples/CMakeLists.txt;0;")
add_test(ctest-three-gpp-channel-example "ns3.36.1-three-gpp-channel-example-default")
set_tests_properties(ctest-three-gpp-channel-example PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/spectrum/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/spectrum/examples/CMakeLists.txt;49;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/spectrum/examples/CMakeLists.txt;0;")
