# CMake generated Testfile for 
# Source directory: /Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/energy/examples
# Build directory: /Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/cmake-cache/src/energy/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-li-ion-energy-source "ns3.36.1-li-ion-energy-source-default")
set_tests_properties(ctest-li-ion-energy-source PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/energy/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/energy/examples/CMakeLists.txt;1;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/energy/examples/CMakeLists.txt;0;")
add_test(ctest-rv-battery-model-test "ns3.36.1-rv-battery-model-test-default")
set_tests_properties(ctest-rv-battery-model-test PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/energy/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/energy/examples/CMakeLists.txt;8;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/energy/examples/CMakeLists.txt;0;")
add_test(ctest-basic-energy-model-test "ns3.36.1-basic-energy-model-test-default")
set_tests_properties(ctest-basic-energy-model-test PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/energy/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/energy/examples/CMakeLists.txt;17;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/energy/examples/CMakeLists.txt;0;")
