# CMake generated Testfile for 
# Source directory: /Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/netanim/examples
# Build directory: /Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/cmake-cache/src/netanim/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-dumbbell-animation "ns3.36.1-dumbbell-animation-default")
set_tests_properties(ctest-dumbbell-animation PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/netanim/examples/CMakeLists.txt;13;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-grid-animation "ns3.36.1-grid-animation-default")
set_tests_properties(ctest-grid-animation PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/netanim/examples/CMakeLists.txt;13;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-star-animation "ns3.36.1-star-animation-default")
set_tests_properties(ctest-star-animation PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/netanim/examples/CMakeLists.txt;13;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-colors-link-description "ns3.36.1-colors-link-description-default")
set_tests_properties(ctest-colors-link-description PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/netanim/examples/CMakeLists.txt;13;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-resources-counters "ns3.36.1-resources-counters-default")
set_tests_properties(ctest-resources-counters PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/netanim/examples/CMakeLists.txt;13;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-wireless-animation "ns3.36.1-wireless-animation-default")
set_tests_properties(ctest-wireless-animation PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/netanim/examples/CMakeLists.txt;23;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-uan-animation "ns3.36.1-uan-animation-default")
set_tests_properties(ctest-uan-animation PROPERTIES  WORKING_DIRECTORY "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/netanim/examples/CMakeLists.txt;36;build_lib_example;/Users/william/Documents/ns-allinone-3.36.1/ns-3.36.1/src/netanim/examples/CMakeLists.txt;0;")
